### ISSUE TITLE
Odd link in readme

### ISSUE THREAD

**Issue by drewish** [krsyoung/redoc-rails#2]
> [https://github.com/almende/vis](https://github.com/almende/vis)

Doesn't seem related to this project so I'm not sure if it's left over copy pasta?

**Comment by drewish** [comment]
Oh looks like it was left over from https://github.com/krsyoung/visjs-rails/blob/master/README.md

**Comment by krsyoung** [comment]
Thanks @drewish, you are 100% right.  I've fixed the link, thanks for taking the time to point this out!
